In [1]:
import tensorflow as tf

In [2]:
# Initialization of Tensors
x = tf.constant(4, shape=(1,1), dtype=tf.float32)
x = tf.constant([[1,2,3], [4,5,6]])

x = tf.ones((3,3))
x = tf.zeros((2,3))
x = tf.eye(3) # Identity Matrix

x = tf.random.normal((3,3), mean=0, stddev=1) # standard normal distribution
x = tf.random.uniform((1,3), minval=0, maxval=1)
x = tf.range(start=1, limit=10, delta=2) # Delta is basically steps
x = tf.cast(x, dtype=tf.float32) # converting between different types
x = tf.cast(x, dtype=tf.int32)

In [14]:
# Mathematical constants
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])
z = tf.add(x,y)
z = tf.subtract(x,y)

z = tf.divide(x, y) # element wise division
z = tf.multiply(x, y) # element wise multiplication
z = tf.tensordot(x, y, axes=1)
z = tf.reduce_sum(x*y, axis=0)

z = x**5 # element wise exponentiate

x = tf.random.normal((2,3))
y = tf.random.normal((3,4))
z = tf.matmul(x, y) # matrix multiplication
z = x @ y # matrix multiplication

In [26]:
# Indexing
x = tf.constant([0,1,1,2,3,1,2,3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1]) # Reverse order

indices = tf.constant([0,3]) # Extracting indices
extract = tf.gather(x, indices)

x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

print(x[0, :])
print(x[0:2, 1])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([2 4], shape=(2,), dtype=int32)


In [33]:
# Reshaping
x = tf.range(9)
x = tf.reshape(x, (3,3))
print(x)
x = tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
